// lang.js
var lang = {
	updateIndexHtml: function() {
		var l = lang[my.lang];
		// innerHTML
		[
			'play-now-btn',
			'create',
			'createTeamBtn',
			'joinPrivateGameBtn',
			'createRankedBtn',
			'joinRankedGame',
			'toggleNation',
			'leaderboardBtn',
			'gameTableName',
			'gameTableMap',
			'gameTableType',
			'friend-status',
			'add-friend',
			'ignore-status',
			'ignore-user',
			'who-account',
			'whisper-account',
			'change-channel',
			'get-help',
			'brokenNet',
			'optionsHeader',
			'musicVolume',
			'soundVolume',
			'bibleMode',
			'windowSize',
			'current-window-size',
			'window-full-screen',
			'window-1920-1080',
			'window-1600-900',
			'window-1360-768',
			'window-1280-720',
			'exit-game',
			'versionSpan',
			'leaderboardRankedBtn',
			'leaderboardFfaBtn',
			'leaderboardTeamBtn',
			'setNationName',
			'submitNationName',
			'setNationFlag',
			'lobbyRankedMatch',
			'lobbyGameNameLabel',
			'lobbyGamePasswordLabel',
			'lobbyGameModeLabel',
			'lobbyGameMapLabel',
			'lobbyMaxPlayersLabel',
			'startGame',
			'cancelGame',
			'confirmSurrenderPrompt',
			'canceSurrenderButtonCancel',
			'canceSurrenderButtonConfirm',
			'hotkey-ui',
			'createGame',
			'createGameHead',
			'createRankedGameHead',
			'createGameNameLabel',
			'createGamePasswordLabel',
			'createGameMaxPlayerLabel',
			'createGameMapLabel',
			'privateGameNameLabel',
			'privateGamePasswordLabel',
			'joinPrivateGameBtnConfirm',
			'cancelGame',
			'cancelGame',
			'cancelGame',
			'cancelGame',
			'cancelGame',
			'cancelGame',
			'cancelGame',
			'joinPrivateGameBtn',
			'abAttack',
			'abSplitAttack',
			'abDeploy',
			'abRush',
			'abBuild',
			'abCannons',
			'abMissile',
			'abNuke',
			'abResearch',
			'abMasonry',
			'abConstruction',
			'abEngineering',
			'abGunpowder',
			'abRocketry',
			'abAtomic',
			'abFuture',
			'reserveLabel',
			'troopsLabel',
			'hud'
		].forEach(function(v) {
			document.getElementById(v).innerHTML = l[_.camelCase(v)];
		});
		// titles/tooltips
		[
			'hide-ui',
			'toggle-flags',
			'hotkeys',
			'gameOptions',
			'surrender',
			'exitSpectate',
			'energy-timer-base',
			'currentYear',
			'energyWrap',
			'foodWrap',
			'scienceWrap',
			'cultureWrap',
			'generalWrap',
			'tacticianWrap',
			'troop-flex',
			'foodBonusTitle',
			'foodMilestoneTitle',
			'scienceBonusTitle',
			'scienceMilestoneTitle',
			'cultureBonusTitle',
			'cultureMilestoneTitle',
			'attack',
			'splitAttack',
			'deploy',
			'rush',
			'upgradeTileDefense',
			'launchNuke',
			'researchMasonry',
			'researchConstruction',
			'researchEngineering',
			'researchGunpowder',
			'researchRocketry',
			'researchAtomicTheory',
			'researchFutureTech',
			'options',
		].forEach(function(v) {
			document.getElementById(v).title = l[_.camelCase(v)];
		})

	},
	english: {
		playerColor: 'Player Color',
		team: 'Team',
		damage: ' damage',
		hudAttack: 'Attack: Select Target',
		hudSplitAttack: 'Split Attack: Select Target',
		hudFireCannons: 'Fire Cannons',
		hudLaunchMissile: 'Launch Missile',
		hudLaunchNuke: 'Launch Nuclear Weapon',
		resourceUiWidth: '22rem',
		selectTarget: 'Select Target',
		reserveLabel: 'Reserve',
		troopsLabel: 'Troops',
		youHaveJoined: 'You have joined the game: ',
		startingGame: "Starting game in ",
		to: 'To ',
		whispers: ' whispers: ',
		joinedChannel: "You have joined channel: ",
		selectTeam: 'Select Team',
		selectPlayerColor: 'Select Player Color',
		difficulties: {
			'Very Easy': 'Very Easy',
			Easy: 'Easy',
			Normal: 'Normal',
			Hard: 'Hard',
			'Very Hard': 'Very Hard',
			Mania: 'Mania',
			Juggernaut: 'Juggernaut'
		},
		governments: {
			Despotism: 'Despotism',
			Monarchy: 'Monarchy',
			Democracy: 'Democracy',
			Fundamentalism: 'Fundamentalism',
			Fascism: 'Fascism',
			Republic: 'Republic',
			Communism: 'Communism',
			Random: 'Random'
		},
		random: 'Random',
		abAttack: "Attack",
		abSplitAttack: "Split Attack",
		abDeploy: "Deploy Troops",
		abRush: "Rush Troops",
		abBuild: "Build",
		abCannons: "Fire Cannons",
		abMissile: "Launch Missile",
		abNuke: "Launch Nuke",
		abResearch: "Research",
		abMasonry: "Masonry",
		abConstruction: "Construction",
		abEngineering: "Engineering",
		abGunpowder: "Gunpowder",
		abRocketry: "Rocketry",
		abAtomic: "Atomic Theory",
		abFuture: "Future Tech",
		hostLeft: "The host has left the lobby.",
		needTwoPlayers: "You need two players to start a game! Wait for players to join or add a computer player to begin.",
		failedToLoad: "Failed to load game data.",
		flagChanged: "Your nation's flag is now: ",
		rankedSearch: "Searching for ranked games...",
		noRankedFound: "No ranked games found!<br>Try creating a ranked game instead.",
		notScience: "Not enough science!",
		needTwoUnits: "You need at least 2 troops to move or attack!",
		maxUnits: "That territory has the maximum number of units!",
		friendlyFire: "Friendly fire! That's your teammate!",
		notEnoughEnergy: 'Not enough energy!',
		notYourTile: 'You do not own that tile.',
		noTroopsAvailable: "No troops available for deployment!",
		badGameName: "Game name must be at least 4-32 characters.",
		notEnoughPlayers: "Game must have 2-8 players.",
		newNationName: "Your new nation name is: ",
		verifyingSteam: "Verifying Steam Credentials...",
		steamNotFound: "Unable to detect Steam. Please launch Steam and try again!",
		logoutSuccess: "Logout successful",
		logoutFailed: "Logout failed",
		ribbonTitle: ['',
			'National Combat Medal',
			'Tactical Nuke Recognition Award',
			'Good Conduct Award',
			"Patriot's Service Ribbon",
			'Civic Service Ribbon',//5
			'Bronze Meritorious Medal',
			'Bronze Service Medal',
			'Bronze Expeditionary Medal',
			'Bronze Cross',
			'Silver Cross',//10
			'Golden Cross',
			'Platinum Cross',
			'Revolutionary Cause Award',
			'Strategic Warfare Award',
			'Combat Service Award', //15
			'Combat Gallantry Award',
			"Stalwart Conqueror's Medal",
			"Dictator's Sword",
			"King's Regalia",
			"Archon's Scales",//20
			'Divine Covenant',
			"Emperor's Fasces",
			"Eagle's Branch",
			"Comrade's Sickle",
			'Golden Expeditionary Medal',//25
			'Golden Meritorious Medal',
			'Golden Service Medal',
			"Champion's Medal",
			"Conqueror's Medal",
			"Commander's Medal",//30
			"Intrepid Heroism Award",
			'Global War Expeditionary Medal',
			'Silver Expeditionary Medal',
			'Silver Meritorious Medal',
			'Silver Service Medal',//35
			"Engineer's Service Ribbon",
		],
		ribbonDescription: ['', // 0
			'Established your nation',
			'Destroyed a fortress with a nuclear weapon',
			'Added two comrades to your friend list',
			'Updated your national flag',
			"Updated your nation's name",//5
			'Won 10 ranked games',
			'Won 10 team games',
			'Won 10 free for all games',
			'Achieved 1800+ rating',
			'Achieved 2100+ rating',//10
			'Achieved 2400+ rating',
			'Achieved 2700+ rating',
			'Great Revolutionary conquered a tile with 100+ units', //13
			'Win a game with a 2-to-1 kill ratio',
			'Won 10 games in a row', // 15
			'Won 25 games in a row',
			'Conquered a tile with a fortress',// 17
			"Won a game under Despotism",
			'Won a game as a Monarchy',
			'Won a game as a Democracy',//20
			'Won a game under Fundamentalism',
			'Won a game under Fascism',
			'Won a game as a Republic',
			'Won a game under Communism',
			'Won 500 free for all games',//25
			'Won 500 ranked games',
			'Won 500 team games',
			"Hit top #10 on the ranked leaderboard",
			"Hit top #100 on the ranked leaderboard",
			"Hit top #1000 on the ranked leaderboard",//30
			"Defeated the Juggernaut",
			'Win an 8-player free for all game',
			'Won 100 free for all games',
			'Won 100 ranked games',
			'Won 100 team games',//35
			'Build a fortress',
		],
		gameNameNotValid: "Game name is not valid!",
		congratulations: "Congratulations!",
		gameVictory: "Your campaign for global domination has succeeded!",
		victory: "Victory",
		armistice: "Armistice!",
		gameArmistice: "The campaign has been suspended!",
		ceaseFire: "Cease Fire",
		defeat: "Defeat!",
		gameDefeat: "Your campaign for world domination has failed!",
		concede: "Concede Defeat",
		spectate: "Spectate",
		defeatIn: "Defeat in ",
		statOverview: "Overview",
		statUnits: "Units",
		statStructures: "Structures",
		statWeapons: "Weapons",
		statResources: "Resources",
		tabUnits: "Units",
		tabStructures: "Structures",
		tabWeapons: "Weapons",
		tabResources: "Resources",
		tabTotalScore: "Total Score",
		tabEarned: "Earned",
		tabDeployed: "Deployed",
		tabKilled: "Killed",
		tabLost: "Lost",
		tabBunkers: "Bunkers",
		tabWalls: "Walls",
		tabFortresses: "Fortresses",
		tabCannons: "Cannons",
		tabMissiles: "Missiles",
		tabNukes: "Nukes",
		tabEnergy: "Energy",
		tabScience: "Science",
		tabFood: "Food",
		tabCulture: "Culture",
		gameDuration: "Game Duration ",
		endGame: "End Game",
		joinPrivateGameBtnConfirm: "Join Game",
		createGameHead: "Free For All Game",
		createRankedGameHead: "Ranked Game",
		createGameNameLabel: "Game Name",
		createGamePasswordLabel: "Password (optional)",
		createGameMaxPlayerLabel: "Maximum Players:",
		createGameMapLabel: "Map",
		createGame: "Create Game",
		createTeamGameHeadLabel: "Team Game",
		noRankedGamesFound: "No ranked games found!<br>Try creating a ranked game instead.",
		privateGameNameLabel: "Game Name",
		privateGamePasswordLabel: "Password",
		confirmSurrenderPrompt: "Surrender? Are You Sure?",
		canceSurrenderButtonCancel: "Cancel",
		canceSurrenderButtonConfirm: "Surrender",
		hotkeyUi: "[V] Toggle the User Interface",
		options: "[ESC] Options",
		researchMasonry: "[Y] Research masonry to unlock bunkers\r\n(20 seconds)",
		researchConstruction: "[O] Research construction to unlock walls\r\n(30 seconds)",
		researchEngineering: "[E] Research engineering to unlock fortresses\r\n(45 seconds)",
		researchGunpowder: "[G] Research gunpowder to unlock cannons\r\n(25 seconds)",
		researchRocketry: "[K] Research rocketry to unlock missiles\r\n(40 seconds)",
		researchAtomicTheory: "[T] Research atomic theory to unlock nuclear weapons\r\n(60 seconds)",
		researchFutureTech: "[F] Research future technology\r\n(90 seconds)",
		attack: "[A] Attack with all troops",
		splitAttack: "[S] Attack with half of your troops",
		deploy: "[D] Deploy reserve troops to a tile",
		rush: "[R] Rush troops from your citizenry. Boosted by culture bonus ",
		defenseLabel: ['Bunker', 'Wall', 'Fortress'],
		boostsTileDefenses: '[B] Boosts tile defenses +',
		reducesWeaponsBy: ' and reduces weapon damage by ',
		fireCannons: '[C] Fire cannons at an adjacent tile. Boosted by Great Generals.\r\n',
		launchMissile: '[M] Launch a missile at any territory. Boosted by Great Generals.\r\n',
		launchNuke: "[N] Launch a nuclear weapon at any territory. Kills 80-99% of troops and destroys all structures.",
		foodBonusTitle: "Food Bonus",
		foodMilestoneTitle: "Food milestones produce reserve troops.",
		scienceBonusTitle: "Science Bonus",
		scienceMilestoneTitle: "Science is used to build structures, fire weapons, and research technology.",
		cultureBonusTitle: "Culture Bonus",
		cultureMilestoneTitle: "Culture milestones produce special rewards.",
		troopFlex: "Deploy troops to conquered territories",
		currentYear: "It's the current year!",
		energyWrap: "Energy is used to attack, move, deploy, and rush troops.",
		foodWrap: "Food milestones produce reserve troops",
		scienceWrap: "Science is used to build structures, weapons, and research technology.",
		cultureWrap: "Culture milestones produce special rewards",
		generalWrap: "Great Generals boost troop attack",
		tacticianWrap: "Great Tacticians boost troop defense",
		energyTimerBase: "Resources update at the end of each turn.",
		hideUi: "[V] Hide User Interface",
		toggleFlags: "Toggle Flags",
		hotkeys: "Hotkeys",
		gameOptions: "[ESC] Options",
		surrender: "Surrender",
		exitSpectate: "Exit Spectate",
		uninhabited: "Uninhabited",
		barbarianTribe: "Barbarian Tribe",
		Despotism: [
			'Free movement through own tiles',
			'Start with gunpowder',
			'Start with a bunker',
			'2x maximum army attack size',
		],
		Monarchy: [
			'+2 defense',
			'+1 culture from 2 food',
			'50% starting culture bonus',
			'+2 cannon damage',
		],
		Democracy: [
			'4x maximum troop deployment',
			'+3 reserve troops when you lose a tile',
			'50% starting science bonus',
			'Reduced culture milestone requirement',
		],
		Fundamentalism: [
			'Overrun: Instant win with 4x advantage',
			'Infiltration: -1 structure defense',
			'Fast growth: Reduced food milestone requirement',
			'+2 troop reward bonus',
		],
		Fascism: [
			'+1 attack',
			'+1 attack from tiles for each defensive structure',
			'+4 attack vs barbarians',
			'Bonus troop with each deployment',
		],
		Republic: [
			'+1 energy',
			'Combat medics heal 50% troops upon victory',
			'Start with masonry',
			'+50% plunder reward bonus from barbarians',
		],
		Communism: [
			'Start with a great person',
			'+1 science from 4 food',
			'Can deploy troops to uninhabited territory',
			'2x discovered reward bonus from barbarians',
		],
		removeCPU: 'Remove CPU',
		addCPU: 'Add CPU',
		lobbyRankedMatch: 'Ranked Match',
		lobbyGameNameLabel: 'Game Name',
		lobbyGamePasswordLabel: 'Password',
		lobbyGameModeLabel: 'Game Mode',
		lobbyGameMapLabel: 'Map',
		lobbyMaxPlayersLabel: 'Max Players',
		startGame: 'Start Game',
		cancelGame: 'Exit',
		setNationName: 'Nation Name',
		submitNationName: 'Update Nation Name',
		setNationFlag: 'National Flag',
		leaderboardRankedBtn: 'Ranked',
		leaderboardFfaBtn: 'Free For All',
		leaderboardTeamBtn: 'Team',
		playNowBtn: 'Play Now',
		create: 'Free For All',
		createTeamBtn: 'Team Game',
		joinPrivateGameBtn: 'Join Private Game',
		createRankedBtn: 'Create Ranked Match',
		joinRankedGame: 'Join Ranked Match',
		toggleNation: 'Configure Nation',
		leaderboardBtn: 'Leaderboard',
		gameTableName: 'Game Name',
		gameTableMap: 'Map',
		gameTableType: 'Type',
		friendStatus: 'Show Friend List',
		addFriend: 'Toggle Friend',
		ignoreStatus: 'Show Ignore List',
		ignoreUser: 'Ignore Account',
		whoAccount: 'Query Account',
		whisperAccount: 'Private Message',
		changeChannel: 'Change Channel',
		getHelp: 'Chat Commands',
		brokenNet: 'Welcome to Broken.net!',
		optionsHeader: 'Options',
		musicVolume: 'Music Volume',
		soundVolume: 'Sound Effect Volume',
		bibleMode: 'Bible Mode',
		windowSize: 'Window Size',
		currentWindowSize: 'Full Screen',
		windowFullScreen: 'Full Screen',
		window19201080: '1920 x 1080',
		window1600900: '1600 x 900',
		window1360768: '1360 x 768',
		window1280720: '1280 x 720',
		exitGame: 'Exit Game',
		versionSpan: 'Version ',
	},
	russian: {
		playerColor: 'Цвет игрока',
		team: 'команда',
		damage: ' наносить ущерб',
		hudAttack: 'Атака: выберите цель',
		hudSplitAttack: 'Сплит-атака: выберите цель',
		hudFireCannons: 'Пожарные пушки',
		hudLaunchMissile: 'Запустить ракету',
		hudLaunchNuke: 'Запуск ядерной бомбы',
		resourceUiWidth: '28rem',
		selectTarget: 'Выберите цель',
		reserveLabel: 'резерв',
		troopsLabel: 'войска',
		youHaveJoined: 'Вы присоединились к игре: ',
		startingGame: "Начало игры в ",
		to: 'к ',
		whispers: ' шепоты: ',
		joinedChannel: "Вы присоединились к каналу: ",
		selectTeam: 'Выбрать команду',
		selectPlayerColor: 'Выберите цвет игрока',
		difficulties: {
			'Very Easy': 'Очень просто',
			Easy: 'Легко',
			Normal: 'Нормальный',
			Hard: 'Жесткий',
			'Very Hard': 'Очень сложно',
			Mania: 'Мания',
			Juggernaut: 'Джаггернаут'
		},
		governments: {
			Despotism: 'Деспотизм',
			Monarchy: 'монархия',
			Democracy: 'демократия',
			Fundamentalism: 'Фундаментализм',
			Fascism: 'Фашизм',
			Republic: 'республика',
			Communism: 'Коммунизм',
			Random: 'случайный'
		},
		random: 'случайный',
		abAttack: "Атака",
		abSplitAttack: "Сплит-атака",
		abDeploy: "Развертывание войск",
		abRush: "Стремительные войска",
		abBuild: "строить",
		abCannons: "Пожарные пушки",
		abMissile: "Запустить ракету",
		abNuke: "Запуск ядерной бомбы",
		abResearch: "Исследование",
		abMasonry: "Каменная кладка",
		abConstruction: "строительство",
		abEngineering: "инженерия",
		abGunpowder: "Порох",
		abRocketry: "ракетная техника",
		abAtomic: "Атомная теория",
		abFuture: "Будущая техника",
		hostLeft: "Хозяин покинул лобби.",
		needTwoPlayers: "Вам нужно два игрока, чтобы начать игру! Подождите, пока игроки присоединятся или добавят компьютерный проигрыватель.",
		failedToLoad: "Не удалось загрузить данные игры.",
		flagChanged: "Флаг вашей страны теперь: ",
		rankedSearch: "Поиск ранжированных игр ...",
		noRankedFound: "Ничего не найдено!<br>Вместо этого попробуйте создать ранжированную игру.",
		notScience: "Недостаточно науки!",
		needTwoUnits: "Вам нужно как минимум 2 войска, чтобы двигаться или атаковать!",
		maxUnits: "Эта территория имеет максимальное количество единиц!",
		friendlyFire: "Дружественный огонь! Это ваш товарищ по команде!",
		notEnoughEnergy: 'Недостаточно энергии!',
		notYourTile: 'У вас нет этой плитки.',
		noTroopsAvailable: "Нет войск для развертывания!",
		badGameName: "Название игры должно быть не менее 4-32 символов.",
		notEnoughPlayers: "В игре должно быть 2-8 игроков.",
		newNationName: "Ваше имя новой нации: ",
		verifyingSteam: "Проверка парольных учетных данных ...",
		steamNotFound: "Не удалось обнаружить Steam. Запустите Steam и повторите попытку!",
		logoutSuccess: "Выход завершен",
		logoutFailed: "Ошибка выхода из системы",
		ribbonTitle: ['',
			'Национальная боевая медаль',
			'Тактическая награда за признание Nuke',
			'Награда за хорошее поведение',
			"патриот Сервисная лента",
			'гражданского Сервисная лента',//5
			'Бронзовая медаль',
			'Медаль Бронзовая служба',
			'Бронзовая экспедиционная медаль',
			'Бронзовый крест',
			'Серебряный крест',//10
			'Золотой Крест',
			'Платиновый крест',
			'Революционная причина',
			'Стратегическая война',
			'Награда за боевые заслуги', //15
			'Боевая награда',
			"Почетная медаль завоевателя",
			"Меч диктатора",
			"Королевские регалии",
			"Весы архонта",//20
			'Божественный завет',
			"Императорский топор",
			"орел Филиал",
			"Топорский серп",
			'Золотая экспедиционная медаль',//25
			'Золотая мерильная медаль',
			'Золотая медаль обслуживания',
			"Чемпионская медаль",
			"Медаль Завоевателя",
			"Медаль командира",//30
			"Премия за непревзойденную героизм",
			'Мировая военная экспедиционная медаль',
			'Серебряная экспедиционная медаль',
			'Серебряная медаль',
			'Серебряная медаль',//35
			"Техническая лента инженера",
		],
		ribbonDescription: ['', // 0
			'Учреждена ваша нация',
			'Разрушена крепость с ядерным оружием',
			'Добавлено два товарища в список друзей',
			'Обновлен ваш национальный флаг',
			"Обновлено название вашей страны",//5
			'Выиграл 10 ранжированных игр',
			'Выиграно 10 командных игр',
			'Выиграл 10 игр бесплатно для всех',
			'Достигнуто 1800+ оценок',
			'Достигнуто 2100+ оценок',//10
			'Достигнуто 2400+ оценок',
			'Достигнуто 2700+ оценок',
			'Великий революционер завоевал плитку с более 100 единицами', //13
			'Выиграйте игру с коэффициентом убийства 2 к 1',
			'Выиграл 10 игр подряд', // 15
			'Выиграл 25 игр подряд',
			'Завоевали плитку с крепостью',// 17
			"Выиграл игру под деспотизмом",
			'Выиграл игру как монархию',
			'Выиграл игру как демократия',//20
			'Выиграл игру под фундаментализмом',
			'Выиграл игру под фашизмом',
			'Выиграл игру как республика',
			'Выиграл игру под коммунизмом',
			'Выиграл 500 бесплатно для всех игр',//25
			'Выиграли 500 ранжированных игр',
			'Выиграно 500 командных матчей',
			"Хит top # 10 в рейтинге лидеров",
			"Хит top # 100 в рейтинге лидеров",
			"Хит top # 1000 в рейтинге лидеров",//30
			"Победил Джаггернаут",
			'Выиграйте 8-плеер бесплатно для всех',
			'Выиграно 100 бесплатных игр для всех',
			'Выиграли 100 ранжированных игр',
			'Выиграно 100 командных матчей',//35
			'Построить крепость',
		],
		gameNameNotValid: "Имя игры недействительно!",
		congratulations: "Поздравления!",
		gameVictory: "Ваша кампания за глобальное господство преуспела!",
		victory: "победа",
		armistice: "прекращение военных действий!",
		gameArmistice: "Кампания приостановлена!",
		ceaseFire: "Прекратить огонь",
		defeat: "Поражение!",
		gameDefeat: "Ваша кампания за мировое господство потерпела неудачу!",
		concede: "уступать поражение",
		spectate: "быть зрителем",
		defeatIn: "Поражение ",
		statOverview: "обзор",
		statUnits: "Единицы",
		statStructures: "сооружения",
		statWeapons: "оружие",
		statResources: "Ресурсы",
		tabUnits: "Единицы",
		tabStructures: "сооружения",
		tabWeapons: "оружие",
		tabResources: "Ресурсы",
		tabTotalScore: "Общий счет",
		tabEarned: "заработанный",
		tabDeployed: "развернутый",
		tabKilled: "убитый",
		tabLost: "Потерял",
		tabBunkers: "Бункеры",
		tabWalls: "стены",
		tabFortresses: "Крепости",
		tabCannons: "Пушки",
		tabMissiles: "Ракеты",
		tabNukes: "Ядерное оружие",
		tabEnergy: "энергии",
		tabScience: "Наука",
		tabFood: "питание",
		tabCulture: "культура",
		gameDuration: "Продолжительность игры ",
		endGame: "Конец игры",
		joinPrivateGameBtnConfirm: "Присоединиться к игре",
		createGameHead: "Бесплатные игры для всех",
		createRankedGameHead: "Рейтинг игры",
		createGameNameLabel: "Название игры",
		createGamePasswordLabel: "Пароль (необязательно)",
		createGameMaxPlayerLabel: "Максимальное количество игроков:",
		createGameMapLabel: "карта",
		createGame: "Создать игру",
		createTeamGameHeadLabel: "Командная игра",
		noRankedGamesFound: "Найденные игры не найдены!<br>Попробуйте создать ранжированную игру вместо.",
		privateGameNameLabel: "Название игры",
		privateGamePasswordLabel: "пароль",
		confirmSurrenderPrompt: "Сдаться? Ты уверен?",
		canceSurrenderButtonCancel: "Отмена",
		canceSurrenderButtonConfirm: "капитуляция",
		hotkeyUi: "Нажмите V, чтобы переключить пользовательский интерфейс.",
		options: "[ESC] Опции",
		researchMasonry: "[Y] Исследовательская кладка для разблокировки бункеров\r\n(20 секунд)",
		researchConstruction: "[O] Исследование строительства для разблокировки стен\r\n(30 секунд)",
		researchEngineering: "[E] Исследовательская разработка для разблокировки крепостей\r\n(45 секунд)",
		researchGunpowder: "[G] Исследовать порох, чтобы разблокировать пушки\r\n(25 секунд)",
		researchRocketry: "[K] Научно-исследовательская ракета для разблокировки ракет\r\n(40 секунд)",
		researchAtomicTheory: "[T] Исследование атомной теории для разблокировки ядерного оружия\r\n(60 секунд)",
		researchFutureTech: "[F] Исследование будущих технологий\r\n(90 секунд)",
		attack: "[A] Атака со всеми войсками",
		splitAttack: "[S] Атака с половиной ваших войск",
		deploy: "[D] Разверните резервные войска на плитку",
		rush: "[R] Выпустите войска из своих граждан. Повышенный бонус за культуру ",
		defenseLabel: ['бункерный', 'стена', 'Крепость'],
		boostsTileDefenses: '[B] Увеличивает защиту от плитки +',
		reducesWeaponsBy: ' и уменьшает урон от оружия ',
		fireCannons: '[C] Огненные пушки на соседней плитке. Подпитывается Великими Генералами.\r\n',
		launchMissile: '[M] Запустить ракету на любой территории. Подпитывается Великими Генералами.\r\n',
		launchNuke: "[N] Запустить ядерную руку на любой территории. Убивает 80-99% солдат и уничтожает все структуры.",
		foodBonusTitle: "Продовольственный бонус",
		foodMilestoneTitle: "Продовольственные вехи производят резервные войска.",
		scienceBonusTitle: "Научный бонус",
		scienceMilestoneTitle: "Наука используется для создания структур, огнестрельного оружия и исследовательских технологий.",
		cultureBonusTitle: "Культурный бонус",
		cultureMilestoneTitle: "Культурные вехи дают особые награды.",
		troopFlex: "Разверните войска на завоеванные территории",
		currentYear: "Это в текущем году!",
		energyWrap: "Энергия используется, чтобы атаковать, перемещать, развертывать и бросать войска.",
		foodWrap: "Продовольственные вехи производят резервные войска",
		scienceWrap: "Наука используется для создания структур, оружия и исследовательских технологий.",
		cultureWrap: "Культурные вехи дают особые награды",
		generalWrap: "Великие генералы повышают атаку войск",
		tacticianWrap: "Великие тактики повышают оборону войск",
		energyTimerBase: "Обновление ресурсов в конце каждого хода.",
		hideUi: "[V] Hide User Interface",
		toggleFlags: "Переключить флаги",
		hotkeys: "Клавиатурный",
		gameOptions: "[ESC] Опции",
		surrender: "капитуляция",
		exitSpectate: "Выход из зрительного зала",
		uninhabited: "необитаемый",
		barbarianTribe: "Племя варваров",
		Despotism: [
			'Свободное передвижение через собственные плитки',
			'Начать с пороха',
			'Начните с бункера',
			'2x максимальный размер атаки армии',
		],
		Monarchy: [
			'+2 защита',
			'+1 культура из 2 блюд',
			'50% старт бонуса культуры',
			'+2 повреждение пушки',
		],
		Democracy: [
			'4x максимальное развертывание войск',
			'+3 резервные войска, когда вы теряете плитку',
			'50% бонус к науке',
			'Требование о минимальном значении культуры',
		],
		Fundamentalism: [
			'перерасход: Мгновенная победа с 4-мя преимуществами',
			'инфильтрация: -1 защита структуры',
			'Быстрый рост: Требование о сокращении потребности в продовольствии',
			'+2 вознаграждение за награду',
		],
		Fascism: [
			'+1 атака',
			'+1 атака из плиток для каждой защитной структуры',
			'+4 атака против варваров',
			'Бонусный отряд с каждым развертыванием',
		],
		Republic: [
			'+1 энергия',
			'Боевые медики излечивают 50% солдат после победы',
			'Начать с кладки',
			'+50% грабительский бонус от варваров',
		],
		Communism: [
			'Начните с отличного человека',
			'+1 наука из 4 блюд',
			'Можно развернуть войска на необитаемой территории',
			'2x открыл бонус от варваров',
		],
		removeCPU: 'удалить компьютер',
		addCPU: 'добавить компьютер',
		lobbyRankedMatch: 'Рейтинг',
		lobbyGameNameLabel: 'Название игры',
		lobbyGamePasswordLabel: 'пароль',
		lobbyGameModeLabel: 'Игровой режим',
		lobbyGameMapLabel: 'карта',
		lobbyMaxPlayersLabel: 'Максимум игроков',
		startGame: 'Начать игру',
		cancelGame: 'Выход',
		setNationName: 'Название страны',
		submitNationName: 'Обновить имя страны',
		setNationFlag: 'Национальный флаг',
		leaderboardRankedBtn: 'Занимает',
		leaderboardFfaBtn: 'Бесплатно для всех',
		leaderboardTeamBtn: 'команда',
		playNowBtn: 'Играть сейчас',
		create: 'Бесплатно для всех',
		createTeamBtn: 'Командная игра',
		joinPrivateGameBtn: 'Присоединиться к частной игре',
		createRankedBtn: 'Создать ранжированный матч',
		joinRankedGame: 'Присоединиться к рейтингу',
		toggleNation: 'Настройка нации',
		leaderboardBtn: 'Лидеры',
		gameTableName: 'Название игры',
		gameTableMap: 'карта',
		gameTableType: 'Тип',
		friendStatus: 'Показать список друзей',
		addFriend: 'Переключить друга',
		ignoreStatus: 'Показать список игнорируемых',
		ignoreUser: 'Игнорировать аккаунт',
		whoAccount: 'Учетная запись',
		whisperAccount: 'Личное сообщение',
		changeChannel: 'Изменить канал',
		getHelp: 'Чат-команды',
		brokenNet: 'Добро пожаловать в Broken.net!',
		optionsHeader: 'Опции',
		musicVolume: 'Объем музыки',
		soundVolume: 'Объем звукового эффекта',
		bibleMode: 'Режим Библии',
		windowSize: 'Размер окна',
		currentWindowSize: 'Полноэкранный',
		windowFullScreen: 'Полноэкранный',
		window19201080: '1920 x 1080',
		window1600900: '1600 x 900',
		window1360768: '1360 x 768',
		window1280720: '1280 x 720',
		exitGame: 'Выход из игры',
		versionSpan: 'Версия ',
	},
	schinese: {
		playerColor: '球员颜色',
		team: '球队',
		damage: ' 损伤',
		hudAttack: '攻击: 选择目标',
        hudSplitAttack: '分开进攻: 选择目标',
        hudFireCannons: '炮火覆盖',
        hudLaunchMissile: '发射导弹',
        hudLaunchNuke: '发射核炸弹',
		resourceUiWidth: '22rem',
		selectTarget: '选择目标',
		reserveLabel: '保留',
		troopsLabel: '部队',
		youHaveJoined: '你已经加入游戏: ',
		startingGame: "游戏即将开始于 ",
		to: '转到 ',
		whispers: ' 讯息: ',
		joinedChannel: "你已经加入频道: ",
		selectTeam: '选择队伍',
		selectPlayerColor: '选择玩家颜色',
		difficulties: {
			'Very Easy': '非常简单',
			Easy: '简单',
			Normal: '正常l',
			Hard: '困难',
			'Very Hard': '非常困难',
			Mania: '狂暴',
			Juggernaut: '巨兽'
		},
		governments: {
			Despotism: '专制',
			Monarchy: '君主制',
			Democracy: '民主制',
			Fundamentalism: '教旨主义',
			Fascism: '法西斯',
			Republic: '共和国',
			Communism: '共产主义',
			Random: '随机'
		},
		random: '随机',
		abAttack: "攻击",
		abSplitAttack: "分开进攻",
		abDeploy: "部署部队",
		abRush: "紧急征召",
		abBuild: "建造",
		abCannons: "炮火覆盖",
		abMissile: "发射导弹",
		abNuke: "发射核炸弹",
		abResearch: "研究",
		abMasonry: "土木工程",
		abConstruction: "建造",
		abEngineering: "工程设施",
		abGunpowder: "火药",
		abRocketry: "火箭发射技术",
		abAtomic: "原子理论",
		abFuture: "先进科技",
		hostLeft: "主机已经离开游戏",
		needTwoPlayers: "你需要两名玩家来开始游戏! 等待另一名玩家以启动游戏.",
		failedToLoad: "读取游戏存档失败",
		flagChanged: "你现在的势力旗帜是: ",
		rankedSearch: "搜寻排位赛...",
		noRankedFound: "未能找到合适的排位赛!<br>你可以试着自己建立一个房间",
		notScience: "研究点数不足!",
		needTwoUnits: "你需要至少两支部队才能移动或者攻击（每个地区必须有一支部队作为守备队）!",
		maxUnits: "该地区驻扎军队数量已经达到上限!",
		friendlyFire: "友军火力误伤! 那是你的队友!",
		notEnoughEnergy: '能量点不足!',
		notYourTile: '你尚未控制那个地块',
		noTroopsAvailable: "没有可部署的部队!",
		badGameName: "游戏名称必须位 4-32 个字符",
		notEnoughPlayers: "游戏必须拥有 2-8 名玩家",
		newNationName: "你的新势力名字是 ",
		verifyingSteam: "校检 Steam 链接...",
		steamNotFound: "无法连接到STEAM，请重新启动STEAM!",
		logoutSuccess: "成功注销",
		logoutFailed: "注销失败",
		ribbonTitle: ['',
			'势力战役勋章',
			'战术核弹勋章',
			'动员组织勋章',
			"爱国者绶带",
			'公民服役绶带',//5
			'青铜荣誉勋章',
			'青铜服役勋章',
			'青铜远征勋章',
			'青铜十字勋章',
			'银十字勋章',//10
			'金十字勋章',
			'白金十字勋章',
			'革命勋章',
			'战争策略家勋章',
			'战斗服役勋章', //15
			'作战勇敢勋章',
			"伟大征服者勋章",
			"独裁者之剑",
			"国王之冠",
			"执政官之秤",//20
			'神圣协议',
			"帝皇法西斯",
			"老鹰后裔",
			"同志，镰刀！",
			'黄金远征勋章',//25
			'黄金荣誉勋章l',
			'黄金荣誉勋章',
			"冠军勋章",
			"征服者勋章",
			"指挥官勋章",//30
			"无畏英雄奖励",
			'全球远征勋章l',
			'白银远征勋章',
			'白银荣誉勋章l',
			'白银服役勋章',//35
			"工程师参站绶带",
		],
		ribbonDescription: ['', // 0
			'创建你自己的势力',
			'用核武器摧毁一处要塞',
			'在好友列表中添加两位共产主义同志',
			'选择势力旗帜',
			"选择势力名称",//5
			'赢得10场排位赛',
			'应当10场小组赛',
			'赢得是10场FFA比赛',
			'段位达到1800+ ',
			'段位达到2100+ ',//10
			'段位达到2400+ ',
			'段位达到2700+ ',
			'用100+的部队占领一个地块', //13
			'以 2比1的伤亡比例获得胜利',
			'赢得10场胜利', // 15
			'赢得25场胜利',
			'夺取敌方一处由要塞控制的地块',// 17
			"专制制度下获得一场胜利",
			'作为君主赢得一场胜利',
			'民主制度下获得一场胜利',//20
			'教旨主义下获得一场胜利',
			'法西斯主义下获得一场胜利',
			'作为共和国赢得一场胜利',
			'共产主义制度下获得一场胜利',
			'赢得500场FFA游戏',//25
			'赢得500场排位赛',
			'赢得500场小组赛',
			"成为排位赛前十名",
			"成为排位赛前一百名",
			"成为排位赛前一千名",//30
			"打败巨兽",
			'赢得一场有八名玩家的FFA比赛',
			'赢得100场FFA比赛',
			'赢得100场排位赛',
			'赢得100场小组赛',//35
			'建造要塞',
		],
		gameNameNotValid: "游戏名称不适合!",
		congratulations: "恭喜!",
		gameVictory: "你已经是世界的统治者!",
		victory: "胜利",
		armistice: "停战!",
		gameArmistice: "战争会暂停一段时间!",
		ceaseFire: "停火",
		defeat: "失败!",
		gameDefeat: "你统治世界的野心破灭了!",
		concede: "承认失败",
		spectate: "观战",
		defeatIn: "失败于 ",
		statOverview: "概况",
		statUnits: "部队",
		statStructures: "建筑",
		statWeapons: "武器",
		statResources: "资源",
		tabUnits: "部队",
		tabStructures: "建筑",
		tabWeapons: "武器",
		tabResources: "资源",
		tabTotalScore: "总分",
		tabEarned: "获得",
		tabDeployed: "部署",
		tabKilled: "歼敌",
		tabLost: "损失",
		tabBunkers: "碉堡",
		tabWalls: "围墙",
		tabFortresses: "要塞",
		tabCannons: "火炮",
		tabMissiles: "导弹",
		tabNukes: "核弹",
		tabEnergy: "能量点",
		tabScience: "研究点",
		tabFood: "食物点",
		tabCulture: "文化点",
		gameDuration: "游戏时间 ",
		endGame: "结束游戏",
		joinPrivateGameBtnConfirm: "加入游戏",
		createGameHead: "允许所有类型的游戏",
		createRankedGameHead: "排位赛",
		createGameNameLabel: "房间名字",
		createGamePasswordLabel: "密码(可选)",
		createGameMaxPlayerLabel: "最大玩家数目:",
		createGameMapLabel: "地图",
		createGame: "创建游戏",
		createTeamGameHeadLabel: "小组赛",
		noRankedGamesFound: "未找到排位赛!<br>T试着自己创建一个房间",
		privateGameNameLabel: "房间名字",
		privateGamePasswordLabel: "密码",
		confirmSurrenderPrompt: "投降? 确定吗?",
		canceSurrenderButtonCancel: "取消",
		canceSurrenderButtonConfirm: "投降",
		hotkeyUi: "[V] 切换用户界面",
		options: "[ESC] 选项",
		researchMasonry: "[Y] 研究土木工程来解锁碉堡\r\n(20 秒)",
		researchConstruction: "[O] 研究建造来解锁围墙\r\n(30 秒)",
		researchEngineering: "[E] 研究工程设施来解锁要塞\r\n(45 秒)",
		researchGunpowder: "[G] 研究火药来解锁获要塞\r\n(25 秒)",
		researchRocketry: "[K] 研究火箭技术来解锁导弹\r\n(40 秒)",
		researchAtomicTheory: "[T] 研究原子学理论来解锁核武器\r\n(60 秒)",
		researchFutureTech: "[F] 研究先进科技\r\n(90 秒)",
		attack: "[A] 用所选全部部队进攻",
		splitAttack: "[S] 用所选一半部队进攻",
		deploy: "[D]部署部队到地块上",
		rush: "[R] 从你的民众中动员部队，文化点对此有影响 ",
		defenseLabel: ['碉堡', '围墙', '要塞'],
		boostsTileDefenses: '[B] 增加地块防御',
		reducesWeaponsBy: ' 并且减少敌军武器杀伤 ',
		fireCannons: '[C]  向某地块进行炮火覆盖， 名将会对此有加成。\r\n',
		launchMissile: '[M] 向某地块发射导弹， 名将会对此有加成。\r\n',
		launchNuke: "[N] 向某地块发射核弹，这会击杀 80-99% 的敌军部队并且摧毁所有建筑 。",
		foodBonusTitle: "食物点加成",
		foodMilestoneTitle: "部队需要食物.",
		scienceBonusTitle: "研究点加成",
		scienceMilestoneTitle: "研究点用于建造建筑，生产火器和研究科技。",
		cultureBonusTitle: "文化点加成",
		cultureMilestoneTitle: "文化点会提供特别奖励",
		troopFlex: "部署部队以略地千里",
		currentYear: "正是此时!",
		energyWrap: "能量点用于攻击，移动，部署和紧急征召部队。",
		foodWrap: "部队需要食物",
		scienceWrap: "研究点用于建造建筑，生产火器和研究科技。",
		cultureWrap: "文化点会提供特别奖励",
		generalWrap: "名将会增加部队攻击力",
		tacticianWrap: "大战略家增加部队防御力",
		energyTimerBase: "每回合结束后点数会增加",
		hideUi: "[V] 隐藏用户界面",
		toggleFlags: "变换旗帜",
		hotkeys: "热键",
		gameOptions: "[ESC] 选项",
		surrender: "投降",
		exitSpectate: "退出观战",
		uninhabited: "无人区",
		barbarianTribe: "蛮族部落",
		Despotism: [
				'己方领土自由移动',
				'火药科技开局',
				'开局拥有一碉堡',
				'攻击力量翻倍',
			],
		Monarchy: [
			'+2 防御',
			'2 食物点加一文化点',
			'文化点获取只有50% ',
			'+2 火炮杀伤',
		],
		Democracy: [
			'4倍陆军部署上限',
			'每失去要给地块获得三支部队',
			'研究点获取只有50% ',
			'减少文化点消耗',
		],
		Fundamentalism: [
			'立即胜利: I取得所有方面 4倍优势后立刻胜利',
			'容易被渗透: -1建筑防御',
			'快速增长: 减少食物消耗',
			'+2 部队奖励奖金',
		],
		Fascism: [
			'+1 攻击',
			'发起攻击的地块每个防御建筑会提供额外的1点攻击力加成',
			'同蛮族作战时+4攻击',
			'部署部队会有奖励',
		],
	 	Republic: [
			'+1 能量点',
			'胜利后会治愈百分之五十的部队',
			'开局拥有土木工程科技',
			'同蛮族作战时+50%  掠夺奖励',
		],
		Communism: [
			'开局时拥有一个伟大领袖',
			'每4食物点加1研究点',
			'能在无人区部署部队',
			'同蛮族作战2x 发现奖励',
		],
		removeCPU: '移除 电脑',
		addCPU: '增加 电脑',
		lobbyRankedMatch: '排位赛',
		lobbyGameNameLabel: '游戏名称',
		lobbyGamePasswordLabel: '密码',
		lobbyGameModeLabel: '游戏模式',
		lobbyGameMapLabel: '地图',
		lobbyMaxPlayersLabel: '最大玩家数目',
		startGame: '开始游戏',
		cancelGame: '退出',
		setNationName: '势力名称',
		submitNationName: '选择势力名称',
		setNationFlag: '势力旗帜',
		leaderboardRankedBtn: '段位',
		leaderboardFfaBtn: '开放',
		leaderboardTeamBtn: '仅队伍',
		playNowBtn: '现在游玩（单机）',
		create: '开放',
		createTeamBtn: '小组赛',
		joinPrivateGameBtn: '加入私人游戏',
		createRankedBtn: '建立排位赛房间',
		joinRankedGame: '加入排位赛',
		toggleNation: '势力配置',
		leaderboardBtn: '记分板',
		gameTableName: '房间名字',
		gameTableMap: '地图',
		gameTableType: '类型',
		friendStatus: '显示好友列表',
		addFriend: '下一个好友',
		ignoreStatus: '展示已忽略列表',
		ignoreUser: '忽略账户',
		whoAccount: '举报账号',
		whisperAccount: '私信',
		changeChannel: '更换频道',
		getHelp: '聊天指令',
		brokenNet: '欢迎来到 Broken.net!',
		optionsHeader: '选项',
		musicVolume: '音乐音量',
		soundVolume: '效果音量',
		bibleMode: '圣经模式',
		windowSize: '窗口化',
		currentWindowSize: '全屏',
		windowFullScreen: ' 全屏',
		window19201080: '1920 x 1080',
		window1600900: '1600 x 900',
		window1360768: '1360 x 768',
		window1280720: '1280 x 720',
		exitGame: '退出游戏',
		versionSpan: '版 ',
	},
	german: {
		playerColor: 'Spielerfarbe',
		team: 'Mannschaft',
		damage: ' Beschädigung',
		hudAttack: 'Attacke: Ziel auswählen',
		hudSplitAttack: 'Split-Angriff: Ziel auswählen',
		hudFireCannons: 'Feuerkanonen',
		hudLaunchMissile: 'Raketen starten',
		hudLaunchNuke: 'Startet die Atombombe',
		resourceUiWidth: '26rem',
		selectTarget: 'Ziel auswählen',
		reserveLabel: 'Reservieren',
		troopsLabel: 'Truppen',
		youHaveJoined: 'Du bist dem Spiel beigetreten: ',
		startingGame: "Spielstart in ",
		to: 'Zu ',
		whispers: ' flüstert: ',
		joinedChannel: "Du bist dem Kanal beigetreten: ",
		selectTeam: 'Team auswählen',
		selectPlayerColor: 'Wählen Sie Spielerfarbe',
		difficulties: {
			'Very Easy': 'Sehr leicht',
			Easy: 'Einfach',
			Normal: 'Normal',
			Hard: 'Hart',
			'Very Hard': 'Sehr schwer',
			Mania: 'Manie',
			Juggernaut: 'Juggernaut'
		},
		governments: {
			Despotism: 'Despotismus',
			Monarchy: 'Monarchie',
			Democracy: 'Demokratie',
			Fundamentalism: 'Fundamentalismus',
			Fascism: 'Faschismus',
			Republic: 'Republik',
			Communism: 'Kommunismus',
			Random: 'Zufällig'
		},
		random: 'Zufällig',
		abAttack: "Attacke",
		abSplitAttack: "Split-Angriff",
		abDeploy: "Bereitstellen von Truppen",
		abRush: "Rush-Truppen",
		abBuild: "Bauen",
		abCannons: "Feuerkanonen",
		abMissile: "Raketen starten",
		abNuke: "Startet die Atombombe",
		abResearch: "Forschung",
		abMasonry: "Mauerwerk",
		abConstruction: "Konstruktion",
		abEngineering: "Ingenieurwesen",
		abGunpowder: "Schießpulver",
		abRocketry: "Raketentechnik",
		abAtomic: "Atomtheorie",
		abFuture: "Zukunft Tech",
		hostLeft: "Der Gastgeber hat die Lobby verlassen.",
		needTwoPlayers: "Du brauchst zwei Spieler, um ein Spiel zu beginnen! Warten Sie, bis die Spieler dem Computer beitreten oder einen Computer hinzufügen.",
		failedToLoad: "Laden der Spieldaten fehlgeschlagen.",
		flagChanged: "Die Fahne deiner Nation ist jetzt: ",
		rankedSearch: "Suche nach Ranglisten-Spielen...",
		noRankedFound: "Keine Ranglistenspiele gefunden!<br>Versuchen Sie stattdessen, ein Ranglisten-Spiel zu erstellen.",
		notScience: "Nicht genug Wissenschaft!",
		needTwoUnits: "Du brauchst mindestens 2 Truppen, um dich zu bewegen oder anzugreifen!",
		maxUnits: "Dieses Gebiet hat die maximale Anzahl von Einheiten!",
		friendlyFire: "Teambeschuss! Das ist dein Teamkollege!",
		notEnoughEnergy: 'Nicht genug Energie!',
		notYourTile: 'Du besitzt diese Kachel nicht.',
		noTroopsAvailable: "Keine Truppen für den Einsatz verfügbar!",
		badGameName: "Der Spielname muss mindestens 4-32 Zeichen lang sein.",
		notEnoughPlayers: "Das Spiel muss 2-8 Spieler haben.",
		newNationName: "Ihr neuer Nationenname ist: ",
		verifyingSteam: "Steam-Anmeldedaten überprüfen...",
		steamNotFound: "Steam kann nicht gefunden werden. Bitte starte Steam und versuche es erneut!",
		logoutSuccess: "Abmeldung erfolgreich",
		logoutFailed: "Abmeldung fehlgeschlagen",
		ribbonTitle: ['',
			'Nationale Kampfmedaille',
			'Tactical Nuke Anerkennungspreis',
			'Preis für gutes Benehmen',
			"Service-Band des Patrioten",
			'Bürgerservice-Band',//5
			'Bronze Verdienstmedaille',
			'Bronze-Service-Medaille',
			'Bronze-Expeditionsmedaille',
			'Bronze Kreuz',
			'Silberkreuz',//10
			'Goldenes Kreuz',
			'Platin-Kreuz',
			'Preis für revolutionäre Zwecke',
			'Strategischer Kriegsführungspreis',
			'Kampfdienst-Auszeichnung', //15
			'Galanterie Auszeichnung',
			"Gewaltige Eroberer-Medaille",
			"Schwert des Diktators",
			"Königs Regalia",
			"Archons Skalen",//20
			'Göttlicher Bund',
			"Kaisers Fasces",
			"Adler Zweig",
			"Genosse Sichel",
			'Goldene Expeditionsmedaille',//25
			'Goldene verdienstvolle Medaille',
			'Goldene Service-Medaille',
			"Meistermedaille",
			"Eroberer-Medaille",
			"Kommandeursmedaille",//30
			"Unerschrockener Heldentumspreis",
			'Expeditionsmedaille des Weltkrieges',
			'Silberne Expeditionsmedaille',
			'Silberne verdienstvolle Medaille',
			'Silberne Service-Medaille',//35
			"Techniker-Serviceband",
		],
		ribbonDescription: ['', // 0
			'Begründete deine Nation',
			'Zerstöre eine Festung mit einer Atomwaffe',
			'Habe zwei Kameraden zu deiner Freundesliste hinzugefügt',
			'Ihre Nationalflagge aktualisiert',
			"Aktualisierte den Namen deiner Nation",//5
			'Gewann 10 Ranglistenspiele',
			'Gewann 10 Mannschaftsspiele',
			'Gewann 10 gratis für alle Spiele',
			'Erreicht 1800+ Bewertung',
			'Erreicht 2100+ Bewertung',//10
			'Erreicht 2400 + Rating',
			'Erreichte 2700+ Bewertung',
			'Große Revolutionäre eroberten eine Kachel mit 100+ Einheiten', //13
			'Gewinne ein Spiel mit einem 2-zu-1-Tötungsverhältnis',
			'Gewann 10 Spiele in Folge', // 15
			'Gewann 25 Spiele in Folge',
			'Eroberte eine Fliese mit einer Festung',// 17
			"Gewann ein Spiel unter Despotismus",
			'Gewann ein Spiel als Monarchie',
			'Gewann ein Spiel als Demokratie',//20
			'Gewann ein Spiel unter Fundamentalismus',
			'Gewann ein Spiel unter Faschismus',
			'Gewann ein Spiel als eine Republik',
			'Gewann ein Spiel unter dem Kommunismus',
			'Gewann 500 gratis für alle Spiele',//25
			'Gewann 500 Ranglistenspiele',
			'Gewann 500 Mannschaftsspiele',
			"Treffe die Top 10 auf der Rangliste",
			"Treffe die Top 100 auf der Rangliste",
			"Treffe die Top # 1000 auf der Rangliste",//30
			"Besiege den Juggernaut",
			'Gewinne ein 8-Spieler-FFA-Spiel',
			'Gewann 100 gratis für alle Spiele',
			'Gewann 100 Ranglistenspiele',
			'Gewann 100 Mannschaftsspiele',//35
			'Baue eine Festung',
		],
		gameNameNotValid: "Der Spielername ist nicht gültig!",
		congratulations: "Herzliche Glückwünsche!",
		gameVictory: "Ihre Kampagne für die globale Vorherrschaft ist gelungen!",
		victory: "Sieg",
		armistice: "Waffenstillstand!",
		gameArmistice: "Die Kampagne wurde ausgesetzt!",
		ceaseFire: "Feuer einstellen",
		defeat: "Niederlage!",
		gameDefeat: "Ihre Kampagne für die Weltherrschaft ist gescheitert!",
		concede: "Concede Niederlage",
		spectate: "Zuschauen",
		defeatIn: "Niederlage in ",
		statOverview: "Überblick",
		statUnits: "Einheiten",
		statStructures: "Strukturen",
		statWeapons: "Waffen",
		statResources: "Ressourcen",
		tabUnits: "Einheiten",
		tabStructures: "Strukturen",
		tabWeapons: "Waffen",
		tabResources: "Ressourcen",
		tabTotalScore: "Gesamtpunktzahl",
		tabEarned: "Verdient",
		tabDeployed: "Bereitgestellt",
		tabKilled: "Getötet",
		tabLost: "Hat verloren",
		tabBunkers: "Bunkers",
		tabWalls: "Wände",
		tabFortresses: "Festungen",
		tabCannons: "Kanonen",
		tabMissiles: "Raketen",
		tabNukes: "Kernwaffen",
		tabEnergy: "Energie",
		tabScience: "Wissenschaft",
		tabFood: "Essen",
		tabCulture: "Kultur",
		gameDuration: "Spieldauer ",
		endGame: "Spiel beenden",
		joinPrivateGameBtnConfirm: "Spiel beitreten",
		createGameHead: "Kostenlos für alle Spiele",
		createRankedGameHead: "Ranglistenspiel",
		createGameNameLabel: "Spielname",
		createGamePasswordLabel: "Passwort (optional)",
		createGameMaxPlayerLabel: "Maximale Spielerzahl:",
		createGameMapLabel: "Karte",
		createGame: "Spiel erstellen",
		createTeamGameHeadLabel: "Teamspiel",
		noRankedGamesFound: "Keine Ranglistenspiele gefunden!<br>Versuchen Sie stattdessen, ein Ranglisten-Spiel zu erstellen.",
		privateGameNameLabel: "Spielname",
		privateGamePasswordLabel: "Passwort",
		confirmSurrenderPrompt: "Kapitulation? Bist du sicher?",
		canceSurrenderButtonCancel: "Stornieren",
		canceSurrenderButtonConfirm: "Kapitulation",
		hotkeyUi: "[V] Wechseln Sie die Benutzeroberfläche",
		options: "[ESC] Optionen",
		researchMasonry: "[Y] Erforsche Mauerwerk, um Bunker freizuschalten\r\n(20 Sekunden)",
		researchConstruction: "[O] Erforschen Sie die Konstruktion, um Wände zu öffnen\r\n(30 Sekunden)",
		researchEngineering: "[E] Forschungstechnik zum Freischalten von Festungen\r\n(45 Sekunden)",
		researchGunpowder: "[G] Erforsche Schießpulver, um Kanonen freizuschalten\r\n(25 Sekunden)",
		researchRocketry: "[K] Research Raketentechnik Raketen zu entsperren\r\n(40 Sekunden)",
		researchAtomicTheory: "[T] Forschung Atomtheorie, um Atomwaffen freizuschalten\r\n(60 Sekunden)",
		researchFutureTech: "[F] Forschung Zukunftstechnologie\r\n(90 Sekunden)",
		attack: "[A] Angriff mit allen Truppen",
		splitAttack: "[S] Greife mit der Hälfte deiner Truppen an",
		deploy: "[D] Setze Reservetruppen auf eine Kachel um",
		rush: "[R] Rush Truppen aus Ihrer Bürgerschaft. Angetrieben durch Kulturbonus ",
		defenseLabel: ['Bunker', 'Mauer', 'Festung'],
		boostsTileDefenses: '[B] Verstärkt die Verteidigung der Fliese +',
		reducesWeaponsBy: ' und reduziert Waffenschaden um ',
		fireCannons: '[C] Feuerkanonen auf einer angrenzenden Fliese. Von großen Generälen beflügelt.\r\n',
		launchMissile: '[M] Starte eine Rakete auf ein beliebiges Territorium. Von großen Generälen beflügelt.\r\n',
		launchNuke: "[N] Startet eine Atomwaffe in jedem Gebiet. Tötet 80-99% der Truppen und zerstört alle Strukturen.",
		foodBonusTitle: "Essensbonus",
		foodMilestoneTitle: "Nahrungsmittelmeilensteine produzieren Reservetruppen.",
		scienceBonusTitle: "Wissenschaftsbonus",
		scienceMilestoneTitle: "Wissenschaft wird verwendet, um Strukturen zu bauen, Feuerwaffen und Forschungstechnologie.",
		cultureBonusTitle: "Kulturbonus",
		cultureMilestoneTitle: "Kulturmeilensteine erzeugen besondere Belohnungen.",
		troopFlex: "Setze Truppen in eroberte Gebiete ein",
		currentYear: "Es ist das laufende Jahr!",
		energyWrap: "Energie wird verwendet, um Truppen anzugreifen, zu bewegen, einzusetzen und zu stürzen.",
		foodWrap: "Nahrungsmittelmeilensteine produzieren Reservetruppen",
		scienceWrap: "Wissenschaft wird verwendet, um Strukturen, Waffen und Forschungstechnologie zu bauen.",
		cultureWrap: "Kulturmeilensteine erzeugen besondere Belohnungen",
		generalWrap: "Große Generäle verstärken Truppenangriffe",
		tacticianWrap: "Große Taktiker verstärken die Truppenabwehr",
		energyTimerBase: "Ressourcen werden am Ende jeder Runde aktualisiert.",
		hideUi: "[V] Benutzerschnittstelle ausblenden",
		toggleFlags: "Flaggen umschalten",
		hotkeys: "Hotkeys",
		gameOptions: "[ESC] Optionen",
		surrender: "Kapitulation",
		exitSpectate: "Spectate verlassen",
		uninhabited: "Unbewohnt",
		barbarianTribe: "Barbarischer Stamm",
		Despotism: [
			'Freizügigkeit durch eigene Fliesen',
			'Beginne mit Schießpulver',
			'Fang mit einem Bunker an',
			'2x maximale Angriffsstärke der Armee',
		],
		Monarchy: [
			'+2 Verteidigung',
			'+1 Kultur aus 2 Lebensmitteln',
			'50% Start Kulturbonus',
			'+2 Kanonenschaden',
		],
		Democracy: [
			'4x maximale Truppentrage',
			'+3 Reserviere Truppen, wenn du ein Plättchen verlierst',
			'50% Start Wissenschaft Bonus',
			'Reduzierte Meilensteinanforderung für die Kultur',
		],
		Fundamentalism: [
			'Overrun: Sofortiger Gewinn mit 4x Vorteil',
			'Infiltration: -1 Strukturverteidigung',
			'Schnelles Wachstum: Reduzierte Essen Meilenstein-Anforderung',
			'+2 Truppenbelohnungsbonus',
		],
		Fascism: [
			'+1 Attacke',
			'+1 Angriff von Kacheln für jede Verteidigungsstruktur',
			'+4 Angriff gegen Barbaren',
			'Bonustruppe bei jeder Bereitstellung',
		],
		Republic: [
			'+1 Energie',
			'Kampfmediziner heilen 50% der Truppen nach dem Sieg',
			'Beginnen Sie mit Mauerwerk',
			'+50% plündern Belohnungsbonus von Barbaren',
		],
		Communism: [
			'Beginne mit einer großartigen Person',
			'+1 Wissenschaft von 4 Essen',
			'Kann Truppen auf unbewohntes Gebiet bringen',
			'2x entdeckte Belohnungsbonus von Barbaren',
		],
		removeCPU: 'Entfernen Sie den Computer',
		addCPU: 'Computer hinzufügen',
		lobbyRankedMatch: 'Ranglisten-Spiel',
		lobbyGameNameLabel: 'Spielname',
		lobbyGamePasswordLabel: 'Passwort',
		lobbyGameModeLabel: 'Spielmodus',
		lobbyGameMapLabel: 'Karte',
		lobbyMaxPlayersLabel: 'Maximale Spieleranzahl',
		startGame: 'Spiel beginnen',
		cancelGame: 'Ausgang',
		setNationName: 'Nationenname',
		submitNationName: 'Nationenname aktualisieren',
		setNationFlag: 'Nationalflagge',
		leaderboardRankedBtn: 'Rangliste',
		leaderboardFfaBtn: 'Frei für alle',
		leaderboardTeamBtn: 'Mannschaft',
		playNowBtn: 'Jetzt spielen',
		create: 'Frei für alle',
		createTeamBtn: 'Teamspiel',
		joinPrivateGameBtn: 'Privates Spiel beitreten',
		createRankedBtn: 'Erstelle Ranglisten-Spiel',
		joinRankedGame: 'Melde dich im Ranglisten-Spiel an',
		toggleNation: 'Konfigurieren Sie Nation',
		leaderboardBtn: 'Bestenliste',
		gameTableName: 'Spielname',
		gameTableMap: 'Karte',
		gameTableType: 'Art',
		friendStatus: 'Freundesliste anzeigen',
		addFriend: 'Toggle Freund',
		ignoreStatus: 'Zeige Ignorierliste',
		ignoreUser: 'Konto ignorieren',
		whoAccount: 'Konto abfragen',
		whisperAccount: 'Private Nachricht',
		changeChannel: 'Kanal wechseln',
		getHelp: 'Chatbefehle',
		brokenNet: 'Willkommen zu Broken.net!',
		optionsHeader: 'Optionen',
		musicVolume: 'Musiklautstärke',
		soundVolume: 'Soundeffekt-Lautstärke',
		bibleMode: 'Bibelmodus',
		windowSize: 'Fenstergröße',
		currentWindowSize: 'Vollbild',
		windowFullScreen: 'Vollbild',
		window19201080: '1920 x 1080',
		window1600900: '1600 x 900',
		window1360768: '1360 x 768',
		window1280720: '1280 x 720',
		exitGame: 'Spiel verlassen',
		versionSpan: 'Ausführung ',
	},
	portuguese: {
		playerColor: 'Cor do Jogador',
		team: 'Equipe',
		damage: ' danificar',
		hudAttack: 'Ataque: selecione o alvo',
		hudSplitAttack: 'Ataque Dividido: Selecionar Alvo',
		hudFireCannons: 'Canhões de fogo',
		hudLaunchMissile: 'Míssil de lançamento',
		hudLaunchNuke: 'Lançar Bomba Nuclear',
		resourceUiWidth: '24rem',
		selectTarget: 'Selecione o alvo',
		reserveLabel: 'reserva',
		troopsLabel: 'Tropas',
		youHaveJoined: 'Você entrou no jogo: ',
		startingGame: "Começando o jogo em ",
		to: 'Para ',
		whispers: ' sussurros: ',
		joinedChannel: "Você entrou no canal: ",
		selectTeam: 'Selecionar time',
		selectPlayerColor: 'Selecione a cor do player',
		difficulties: {
			'Very Easy': 'Muito fácil',
			Easy: 'Fácil',
			Normal: 'Normal',
			Hard: 'Difícil',
			'Very Hard': 'Muito difícil',
			Mania: 'Mania',
			Juggernaut: 'Juggernaut'
		},
		governments: {
			Despotism: 'Despotismo',
			Monarchy: 'Monarquia',
			Democracy: 'Democracia',
			Fundamentalism: 'Fundamentalismo',
			Fascism: 'Fascismo',
			Republic: 'República',
			Communism: 'O comunismo',
			Random: 'Aleatória'
		},
		random: 'Aleatória',
		abAttack: "Ataque",
		abSplitAttack: "Ataque Dividido",
		abDeploy: "Implantar tropas",
		abRush: "Tropas de pressa",
		abBuild: "Construir",
		abCannons: "Canhões de fogo",
		abMissile: "Míssil de lançamento",
		abNuke: "Lançar Bomba Nuclear",
		abResearch: "Pesquisa",
		abMasonry: "Alvenaria",
		abConstruction: "Construção",
		abEngineering: "Engenharia",
		abGunpowder: "Pólvora",
		abRocketry: "Foguetes",
		abAtomic: "Teoria atômica",
		abFuture: "Tech futuro",
		hostLeft: "O anfitrião deixou o saguão.",
		needTwoPlayers: "Você precisa de dois jogadores para começar um jogo! Aguarde que os jogadores participem ou adicionem um player de computador para começar.",
		failedToLoad: "Falha ao carregar dados do jogo.",
		flagChanged: "A bandeira do seu país é agora: ",
		rankedSearch: "Procurando por jogos classificados...",
		noRankedFound: "Nenhum jogo classificado encontrado!<br>Tente criar um jogo classificado.",
		notScience: "Ciência insuficiente!",
		needTwoUnits: "Você precisa de pelo menos 2 tropas para se mover ou atacar!",
		maxUnits: "Esse território tem o número máximo de unidades!",
		friendlyFire: "Fogo amigo! Esse é seu companheiro de equipe!",
		notEnoughEnergy: 'Energia não suficiente!',
		notYourTile: 'Você não possui esse bloco.',
		noTroopsAvailable: "Nenhuma tropa disponível para implantação!",
		badGameName: "O nome do jogo deve ter pelo menos 4 a 32 caracteres.",
		notEnoughPlayers: "O jogo deve ter 2-8 jogadores.",
		newNationName: "Seu novo nome da nação é: ",
		verifyingSteam: "Verificando as credenciais do Steam...",
		steamNotFound: "Não é possível detectar o Steam. Por favor, inicie o Steam e tente novamente!",
		logoutSuccess: "Logout com sucesso",
		logoutFailed: "Logout falhou",
		ribbonTitle: ['',
			'Medalha Nacional de Combate',
			'Prêmio de Reconhecimento Nuke Tático',
			'Prêmio de boa conduta',
			"Faixa de serviço do patriota",
			'Faixa de serviço cívico',//5
			'Medalha Meritória de Bronze',
			'Medalha de Serviço Bronze',
			'Medalha Expedicionária de Bronze',
			'Cruz de bronze',
			'Cruz de prata',//10
			'Cruz dourada',
			'Cruz de Platina',
			'Prêmio de Causa Revolucionária',
			'Prêmio de Guerra Estratégica',
			'Prêmio de serviço de combate', //15
			'Prêmio Galanteador de Combate',
			"Medalha do Conquistador Stalwart",
			"Espada do Ditador",
			"Regalia do rei",
			"Escalas de Arconte",//20
			'Convênio Divino',
			"Fasces do Imperador",
			"Filial da Águia",
			"Foice de Camarada",
			'Medalha Expedicionária Dourada',//25
			'Medalha Meritória Dourada',
			'Medalha de Serviço de Ouro',
			"Medalha do Campeão",
			"Medalha do Conquistador",
			"Medalha do Comandante",//30
			"Prêmio de heroísmo intrépido",
			'Medalha Expedicionária Global de Guerra ',
			'Medalha Expedicionária de Prata',
			'Medalha Meritória de Prata',
			'Medalha de Serviço de Prata',//35
			"Faixa de serviço do engenheiro",
		],
		ribbonDescription: ['', // 0
			'Estabeleceu sua nação',
			'Destruiu uma fortaleza com uma arma nuclear',
			'Adicionado dois camaradas à sua lista de amigos',
			'Atualizou sua bandeira nacional',
			"Atualizou o nome da sua nação",//5
			'Ganhou 10 jogos classificados',
			'Ganhou 10 jogos de equipe',
			'Ganhou 10 grátis para todos os jogos',
			'Alcançou a classificação de 1800+',
			'Alcançou 2100+ classificação',//10
			'Achieved 2400+ rating',
			'Achieved 2700+ rating',
			'Grande Revolucionário conquistou uma telha com mais de 100 unidades', //13
			'Ganhe um jogo com uma razão de 2 para 1 de mortes',
			'Ganhou 10 jogos seguidos', // 15
			'Ganhou 25 jogos seguidos',
			'Conquistou uma telha com uma fortaleza',// 17
			"Ganhou um jogo sob Despotismo",
			'Ganhou um jogo como Monarquia',
			'Ganhou um jogo como uma democracia',//20
			'Ganhou um jogo sob o fundamentalismo',
			'Ganhou um jogo sob o fascismo',
			'Ganhou um jogo como uma república',
			'Ganhou um jogo sob o comunismo',
			'Ganhou 500 grátis para todos os jogos',//25
			'Ganhou 500 jogos classificados',
			'Ganhou 500 jogos de equipe',
			"Atingir o top 10 na classificação geral",
			"Atingir o top # 100 na classificação geral",
			"Atingiu o topo # 1000 no ranking de classificação",//30
			"Derrotou o Juggernaut",
			'Ganhe um 8 jogadores grátis para todos os jogos',
			'Ganhou 100 livres para todos os jogos',
			'Ganhou 100 jogos classificados',
			'Ganhou 100 jogos de equipe',//35
			'Construa uma fortaleza',
		],
		gameNameNotValid: "O nome do jogo não é válido!",
		congratulations: "Parabéns!",
		gameVictory: "Sua campanha pela dominação global foi bem sucedida!",
		victory: "Vitória",
		armistice: "Armistício!",
		gameArmistice: "A campanha foi suspensa!",
		ceaseFire: "Cessar fogo",
		defeat: "Derrota!",
		gameDefeat: "Sua campanha pela dominação do mundo falhou!",
		concede: "Reconhecer a derrota",
		spectate: "Olhar",
		defeatIn: "Derrota em ",
		statOverview: "Visão geral",
		statUnits: "Unidades",
		statStructures: "Estruturas",
		statWeapons: "Armas",
		statResources: "Recursos",
		tabUnits: "Unidades",
		tabStructures: "Estruturas",
		tabWeapons: "Armas",
		tabResources: "Recursos",
		tabTotalScore: "Pontuação total",
		tabEarned: "Ganhou",
		tabDeployed: "Implantado",
		tabKilled: "Morto",
		tabLost: "Perdido",
		tabBunkers: "Bunkers",
		tabWalls: "Paredes",
		tabFortresses: "Fortalezas",
		tabCannons: "Canhões",
		tabMissiles: "Mísseis",
		tabNukes: "Armas nucleares",
		tabEnergy: "Energia",
		tabScience: "Ciência",
		tabFood: "Comida",
		tabCulture: "Cultura",
		gameDuration: "Duração do Jogo ",
		endGame: "Jogo final",
		joinPrivateGameBtnConfirm: "Entrar no jogo",
		createGameHead: "Grátis para todos os jogos",
		createRankedGameHead: "Jogo classificado",
		createGameNameLabel: "Nome do jogo",
		createGamePasswordLabel: "Senha (opcional)",
		createGameMaxPlayerLabel: "Máximo de Jogadores:",
		createGameMapLabel: "Mapa",
		createGame: "Criar jogo",
		createTeamGameHeadLabel: "Jogo de equipe",
		noRankedGamesFound: "Nenhum jogo classificado encontrado!<br>Tente criar um jogo classificado.",
		privateGameNameLabel: "Nome do jogo",
		privateGamePasswordLabel: "Senha",
		confirmSurrenderPrompt: "Entrega?",
		canceSurrenderButtonCancel: "Cancelar",
		canceSurrenderButtonConfirm: "Entrega",
		hotkeyUi: "[V] Alternar a interface do usuário",
		options: "[ESC] Opções",
		researchMasonry: "[Y] Pesquisa de alvenaria para destravar bunkers\r\n(20 segundos)",
		researchConstruction: "[O] Construção de pesquisa para desbloquear paredes\r\n(30 segundos)",
		researchEngineering: "[E] Engenharia de pesquisa para desbloquear fortalezas\r\n(45 segundos)",
		researchGunpowder: "[G] Pesquisa de pólvora para desbloquear canhões\r\n(25 segundos)",
		researchRocketry: "[K] Pesquisa de foguetes para desbloquear mísseis\r\n(40 segundos)",
		researchAtomicTheory: "[T] Pesquise teoria atômica para desbloquear armas nucleares\r\n(60 segundos)",
		researchFutureTech: "[F] Tecnologia de pesquisa futura\r\n(90 segundos)",
		attack: "[A] Ataque com todas as tropas",
		splitAttack: "[S] Ataque com metade de suas tropas",
		deploy: "[D] Implantar tropas de reserva em um ladrilho",
		rush: "[R] Apresse as tropas de seus cidadãos. Impulsionado pelo bônus cultural ",
		defenseLabel: ['Bunker', 'parede', 'Fortaleza'],
		boostsTileDefenses: '[B] Aumenta as defesas do azulejo +',
		reducesWeaponsBy: ' e reduz dano de arma por ',
		fireCannons: '[C] Canhões de fogo em uma telha adjacente. Impulsionado por grandes generais.\r\n',
		launchMissile: '[M] Lançar um míssil em qualquer território. Impulsionado por grandes generais.\r\n',
		launchNuke: "[N] Lance uma arma nuclear em qualquer território. Mata 80-99% das tropas e destrói todas as estruturas.",
		foodBonusTitle: "Bônus Alimentar",
		foodMilestoneTitle: "Marcos miliários de alimentos produzem tropas de reserva.",
		scienceBonusTitle: "Bônus da Ciência",
		scienceMilestoneTitle: "A ciência é usada para construir estruturas, armas de fogo e tecnologia de pesquisa.",
		cultureBonusTitle: "Bônus de Cultura",
		cultureMilestoneTitle: "Marcos de cultura produzem recompensas especiais.",
		troopFlex: "Implantar tropas em territórios conquistados",
		currentYear: "É o ano corrente!",
		energyWrap: "A energia é usada para atacar, mover, implantar e apressar as tropas.",
		foodWrap: "Marcos miliários de alimentos produzem tropas de reserva",
		scienceWrap: "A ciência é usada para construir estruturas, armas e tecnologia de pesquisa.",
		cultureWrap: "Marcos de cultura produzem recompensas especiais",
		generalWrap: "Grandes generais aumentam ataque de tropas",
		tacticianWrap: "Grandes táticos reforçam defesa de tropas",
		energyTimerBase: "Atualização de recursos no final de cada turno.",
		hideUi: "[V] Ocultar interface do usuário",
		toggleFlags: "Alternar sinalizadores",
		hotkeys: "Teclas de atalho",
		gameOptions: "[ESC] Opções",
		surrender: "Entrega",
		exitSpectate: "Sair de Espectador",
		uninhabited: "Desabitada",
		barbarianTribe: "Tribo Bárbara",
		Despotism: [
			'Livre circulação através de telhas próprias',
			'Comece com a pólvora',
			'Comece com um bunker',
			'2x tamanho máximo de ataque do exército',
		],
		Monarchy: [
			'+2 defesa',
			'+1 cultura de 2 alimentos',
			'50% começando bônus cultural',
			'+2 dano de canhão',
		],
		Democracy: [
			'4x implantação máxima de tropas',
			'+3 tropas de reserva quando você perde um azulejo',
			'50% começando bônus de ciência',
			'Requisito de marco de cultura reduzido',
		],
		Fundamentalism: [
			'Superação: vitória instantânea com vantagem de 4x',
			'Infiltração: -1 estrutura de defesa',
			'Crescimento rápido: exigência de marcos alimentares reduzidos',
			'+2 bônus de recompensa de tropas',
		],
		Fascism: [
			'+1 ataque',
			'+1 ataque de telhas para cada estrutura defensiva',
			'+4 ataque vs bárbaros',
			'Tropa de bônus com cada implantação',
		],
		Republic: [
			'+1 energia',
			'Médicos de combate curam 50% das tropas após a vitória',
			'Comece com alvenaria',
			'+50% saqueie bónus de recompensa dos bárbaros',
		],
		Communism: [
			'Comece com uma ótima pessoa',
			'+1 ciência de 4 alimentos',
			'Pode implantar tropas em território desabitado',
			'2x bônus de recompensa descoberto de bárbaros',
		],
		removeCPU: 'Remover computador',
		addCPU: 'Adicionar computador',
		lobbyRankedMatch: 'Partida ranqueada',
		lobbyGameNameLabel: 'Nome do jogo',
		lobbyGamePasswordLabel: 'Senha',
		lobbyGameModeLabel: 'Modo de jogo',
		lobbyGameMapLabel: 'Mapa',
		lobbyMaxPlayersLabel: 'Máximo de jogadores',
		startGame: 'Começar o jogo',
		cancelGame: 'Saída',
		setNationName: 'Nome da nação',
		submitNationName: 'Atualizar nome da nação',
		setNationFlag: 'Bandeira nacional',
		leaderboardRankedBtn: 'Classificados',
		leaderboardFfaBtn: 'Grátis para todos',
		leaderboardTeamBtn: 'Equipe',
		playNowBtn: 'Jogue agora',
		create: 'Grátis para todos',
		createTeamBtn: 'Jogo de equipe',
		joinPrivateGameBtn: 'Participe do Jogo Privado',
		createRankedBtn: 'Criar um jogo classificado',
		joinRankedGame: 'Junte-se ao jogo classificado',
		toggleNation: 'Configurar nação',
		leaderboardBtn: 'Entre os melhores',
		gameTableName: 'Nome do jogo',
		gameTableMap: 'Mapa',
		gameTableType: 'Tipo',
		friendStatus: 'Mostrar lista de amigos',
		addFriend: 'Alternar Amigo',
		ignoreStatus: 'Mostrar lista de ignorados',
		ignoreUser: 'Ignorar conta',
		whoAccount: 'Conta de Consulta',
		whisperAccount: 'Mensagem privada',
		changeChannel: 'Mude o canal',
		getHelp: 'Comandos de Chat',
		brokenNet: 'Bem-vindo ao Broken.net!',
		optionsHeader: 'Opções',
		musicVolume: 'Volume da música',
		soundVolume: 'Volume do efeito sonoro',
		bibleMode: 'Modo Bíblico',
		windowSize: 'Tamanho da janela',
		currentWindowSize: 'Tela cheia',
		windowFullScreen: 'Tela cheia',
		window19201080: '1920 x 1080',
		window1600900: '1600 x 900',
		window1360768: '1360 x 768',
		window1280720: '1280 x 720',
		exitGame: 'Sair do jogo',
		versionSpan: 'Versão ',
	},
	alternateSupportedLanguages: [
		'russian', //1
		'schinese',
		'german',
		'portuguese'
	],
	apiLanguageCode: [
		'arabic',
		'bulgarian',
		'schinese', //5
		'tchinese',
		'czech',
		'danish',
		'dutch',
		'finnish', //13
		'french', //4
		'german', //2
		'greek', //14
		'hungarian',
		'italian', //7
		'japanese', //12
		'koreana', //11
		'norwegian',
		'polish', //9
		'portuguese', //3
		'brazilian',
		'romanian',
		'russian', //1
		'spanish', //6
		'swedish',
		'thai',
		'turkish', //10
		'ukrainian', //8
	]
};
