// lang.js
var lang = {
	updateIndexHtml: function() {
		var l = lang[my.lang];
		// innerHTML
		[
			{ id: 'play-now-btn', text: l.playNowBtn },
			{ id: 'create', text: l.create },
			{ id: 'createTeamBtn', text: l.createTeamBtn },
			{ id: 'joinPrivateGameBtn', text: l.joinPrivateGameBtn },
			{ id: 'createRankedBtn', text: l.createRankedBtn },
			{ id: 'joinRankedGame', text: l.joinRankedGame },
			{ id: 'toggleNation', text: l.toggleNation },
			{ id: 'leaderboardBtn', text: l.leaderboardBtn },
			{ id: 'gameTableName', text: l.gameTableName },
			{ id: 'gameTableMap', text: l.gameTableMap },
			{ id: 'gameTableType', text: l.gameTableType },
			{ id: 'friend-status', text: l.friendStatus },
			{ id: 'add-friend', text: l.addFriend },
			{ id: 'ignore-status', text: l.ignoreStatus },
			{ id: 'ignore-user', text: l.ignoreUser },
			{ id: 'who-account', text: l.whoAccount },
			{ id: 'whisper-account', text: l.whisperAccount },
			{ id: 'change-channel', text: l.changeChannel },
			{ id: 'get-help', text: l.getHelp },
			{ id: 'brokenNet', text: l.brokenNet },
			{ id: 'optionsHeader', text: l.optionsHeader },
			{ id: 'musicVolume', text: l.musicVolume },
			{ id: 'soundVolume', text: l.soundVolume },
			{ id: 'bibleMode', text: l.bibleMode },
			{ id: 'windowSize', text: l.windowSize },
			{ id: 'current-window-size', text: l.currentWindowSize },
			{ id: 'window-full-screen', text: l.windowFullScreen },
			{ id: 'window-1920-1080', text: l.window19201080},
			{ id: 'window-1600-900', text: l.window1600900 },
			{ id: 'window-1360-768', text: l.window1360768 },
			{ id: 'window-1280-720', text: l.window1280720 },
			{ id: 'exit-game', text: l.exitGame},
			{ id: 'versionSpan', text: l.versionSpan },
			{ id: 'leaderboardRankedBtn', text: l.leaderboardRankedBtn },
			{ id: 'leaderboardFFABtn', text: l.leaderboardFFABtn },
			{ id: 'leaderboardTeamBtn', text: l.leaderboardTeamBtn },
			{ id: 'setNationName', text: l.setNationName },
			{ id: 'submitNationName', text: l.submitNationName },
			{ id: 'setNationFlag', text: l.setNationFlag },
			{ id: 'lobbyRankedMatch', text: l.lobbyRankedMatch },
			{ id: 'lobbyGameNameLabel', text: l.lobbyGameNameLabel },
			{ id: 'lobbyGamePasswordLabel', text: l.lobbyGamePasswordLabel },
			{ id: 'lobbyGameModeLabel', text: l.lobbyGameModeLabel },
			{ id: 'lobbyGameMapLabel', text: l.lobbyGameMapLabel },
			{ id: 'lobbyMaxPlayersLabel', text: l.lobbyMaxPlayersLabel },
			{ id: 'startGame', text: l.startGame },
			{ id: 'cancelGame', text: l.cancelGame },
			{ id: 'confirmSurrenderPrompt', text: l.confirmSurrenderPrompt },
			{ id: 'canceSurrenderButtonCancel', text: l.canceSurrenderButtonCancel },
			{ id: 'canceSurrenderButtonConfirm', text: l.canceSurrenderButtonConfirm },
			{ id: 'hotkey-ui', text: l.hotkeyUi },
			{ id: 'cancelGame', text: l.cancelGame },
		].forEach(function(v) {
			document.getElementById(v.id).innerHTML = v.text;
		});
		// titles/tooltips
		[
			{ id: 'hide-ui', text: l.hideUI },
			{ id: 'toggle-flags', text: l.toggleFlags },
			{ id: 'hotkeys', text: l.hotkeys },
			{ id: 'gameOptions', text: l.gameOptions },
			{ id: 'surrender', text: l.surrender },
			{ id: 'exitSpectate', text: l.exitSpectate },
			{ id: 'energy-timer-base', text: l.energyTimerBase },
			{ id: 'currentYear', text: l.currentYear },
			{ id: 'energyWrap', text: l.energyWrap },
			{ id: 'foodWrap', text: l.foodWrap },
			{ id: 'scienceWrap', text: l.scienceWrap },
			{ id: 'cultureWrap', text: l.cultureWrap },
			{ id: 'generalWrap', text: l.generalWrap },
			{ id: 'tacticianWrap', text: l.tacticianWrap },
			{ id: 'troop-flex', text: l.troopFlex },
			{ id: 'foodBonusTitle', text: l.foodBonusTitle },
			{ id: 'foodMilestoneTitle', text: l.foodMilestoneTitle },
			{ id: 'scienceBonusTitle', text: l.scienceBonusTitle },
			{ id: 'scienceMilestoneTitle', text: l.scienceMilestoneTitle },
			{ id: 'cultureBonusTitle', text: l.cultureBonusTitle },
			{ id: 'cultureMilestoneTitle', text: l.cultureMilestoneTitle },
			{ id: 'attack', text: l.attack },
			{ id: 'splitAttack', text: l.splitAttack },
			{ id: 'deploy', text: l.deploy },
			{ id: 'rush', text: l.rush },
			{ id: 'upgradeTileDefense', text: l.upgradeTileDefense },
			{ id: 'launchNuke', text: l.launchNuke },
			{ id: 'researchMasonry', text: l.researchMasonry },
			{ id: 'researchConstruction', text: l.researchConstruction },
			{ id: 'researchEngineering', text: l.researchEngineering },
			{ id: 'researchGunpowder', text: l.researchGunpowder },
			{ id: 'researchRocketry', text: l.researchRocketry },
			{ id: 'researchAtomicTheory', text: l.researchAtomicTheory },
			{ id: 'researchFutureTech', text: l.researchFutureTech },
		].forEach(function(v) {
			document.getElementById(v.id).title = v.text;
		})

	},
	'english': {
		confirmSurrenderPrompt: "Surrender? Are You Sure?",
		canceSurrenderButtonCancel: "Cancel",
		canceSurrenderButtonConfirm: "Surrender",
		hotkeyUi: "Press V to Toggle the UI",
		researchMasonry: "Research masonry to unlock bunkers\r\n(20 seconds)",
		researchMasonry: "Research masonry to unlock bunkers\r\n(20 seconds)",
		researchMasonry: "Research masonry to unlock bunkers\r\n(20 seconds)",
		researchConstruction: "Research construction to unlock walls\r\n(30 seconds)",
		researchEngineering: "Research engineering to unlock fortresses\r\n(45 seconds)",
		researchGunpowder: "Research gunpowder to unlock cannons\r\n(25 seconds)",
		researchRocketry: "Research rocketry to unlock missiles\r\n(40 seconds)",
		researchAtomicTheory: "Research atomic theory to unlock nuclear weapons\r\n(60 seconds)",
		researchFutureTech: "Research future technology\r\n(90 seconds)",
		attack: "Attack with all troops",
		splitAttack: "Attack with half of your troops",
		deploy: "Deploy reserve troops to a tile",
		rush: "Rush troops from your citizenry. Boosted by culture bonus ",
		upgradeTileDefense: "Bunkers boost tile defense +1",
		defenseLabel: ['Bunker', 'Wall', 'Fortress'],
		boostsTileDefenses: 'Boosts tile defenses +',
		reducesWeaponsBy: ' and reduces weapon damage by ',
		fireCannons: 'Fire cannons at an adjacent tile. Boosted by Great Generals.\r\n',
		launchMissile: 'Launch a missile at any territory. Boosted by Great Generals.\r\n',
		launchNuke: "Launch a nuclear weapon at any territory. Kills 80-99% of troops and destroys all structures.",
		foodBonusTitle: "Food Bonus",
		foodMilestoneTitle: "Food milestones produce reserve troops.",
		scienceBonusTitle: "Science Bonus",
		scienceMilestoneTitle: "Science is used to build structures, fire weapons, and research technology.",
		cultureBonusTitle: "Culture Bonus",
		cultureMilestoneTitle: "Culture milestones produce special rewards.",
		troopFlex: "Deploy troops to conquered territories",
		currentYear: "It's the current year!",
		energyWrap: "Energy is used to attack, move, deploy, and rush troops.",
		foodWrap: "Food milestones produce reserve troops",
		scienceWrap: "Science is used to build structures, weapons, and research technology.",
		cultureWrap: "Culture milestones produce special rewards",
		generalWrap: "Great Generals boost troop attack",
		tacticianWrap: "Great Tacticians boost troop defense",
		energyTimerBase: "Resources update at the end of each turn.",
		hideUI: "Hide User Interface",
		toggleFlags: "Toggle Flags",
		hotkeys: "Hotkeys",
		gameOptions: "Options",
		surrender: "Surrender",
		exitSpectate: "Exit Spectate",
		uninhabited: "Uninhabited",
		barbarianTribe: "Barbarian Tribe",
		Despotism: [
			'Free movement through own tiles',
			'Start with gunpowder',
			'Start with a bunker',
			'2x maximum army attack size',
		],
		Monarchy: [
			'+2 defense',
			'+1 culture from 2 food',
			'50% starting culture bonus',
			'+2 cannon damage',
		],
		Democracy: [
			'4x maximum troop deployment',
			'+3 reserve troops when you lose a tile',
			'50% starting science bonus',
			'Reduced culture milestone requirement',
		],
		Fundamentalism: [
			'Overrun: Instant win with 4x advantage',
			'Infiltration: -1 structure defense',
			'Fast growth: Reduced food milestone requirement',
			'+2 troop reward bonus',
		],
		Fascism: [
			'+1 attack',
			'+1 attack from tiles for each defensive structure',
			'+4 attack vs barbarians',
			'Bonus troop with each deployment',
		],
		Republic: [
			'+1 energy',
			'Combat medics heal 50% troops upon victory',
			'Start with masonry',
			'+50% plunder reward bonus from barbarians',
		],
		Communism: [
			'Start with a great person',
			'+1 science from 4 food',
			'Can deploy troops to uninhabited territory',
			'2x discovered reward bonus from barbarians',
		],
		removeCPU: 'Remove CPU',
		addCPU: 'Add CPU',
		lobbyRankedMatch: 'Ranked Match',
		lobbyGameNameLabel: 'Game Name',
		lobbyGamePasswordLabel: 'Password',
		lobbyGameModeLabel: 'Game Mode',
		lobbyGameMapLabel: 'Map',
		lobbyMaxPlayersLabel: 'Max Players',
		startGame: 'Start Game',
		cancelGame: 'Exit',
		setNationName: 'Nation Name',
		submitNationName: 'Update Nation Name',
		setNationFlag: 'National Flag',
		leaderboardRankedBtn: 'Ranked',
		leaderboardFFABtn: 'Free For All',
		leaderboardTeamBtn: 'Team',
		playNowBtn: 'Play Now',
		create: 'Free For All',
		createTeamBtn: 'Team Game',
		joinPrivateGameBtn: 'Join Private Game',
		createRankedBtn: 'Create Ranked Match',
		joinRankedGame: 'Join Ranked Match',
		toggleNation: 'Configure Nation',
		leaderboardBtn: 'Leaderboard',
		gameTableName: 'Game Name',
		gameTableMap: 'Map',
		gameTableType: 'Type',
		friendStatus: 'Show Friend List',
		addFriend: 'Toggle Friend',
		ignoreStatus: 'Show Ignore List',
		ignoreUser: 'Ignore Account',
		whoAccount: 'Query Account',
		whisperAccount: 'Private Message',
		changeChannel: 'Change Channel',
		getHelp: 'Chat Commands',
		brokenNet: 'Welcome to Broken.net!',
		optionsHeader: 'Options',
		musicVolume: 'Music Volume',
		soundVolume: 'Sound Effect Volume',
		bibleMode: 'Bible Mode',
		windowSize: 'Window Size',
		currentWindowSize: 'Full Screen',
		windowFullScreen: 'Full Screen',
		window19201080: '1920 x 1080',
		window1600900: '1600 x 900',
		window1360768: '1360 x 768',
		window1280720: '1280 x 720',
		exitGame: 'Exit Game',
		versionSpan: 'Version ',
	}
};
