#!/bin/bash
#make-run.sh
#make sure a process is always running.

#export DISPLAY=:0 
#needed if you are running a simple gui app.

process=push-server.php
makerun="/usr/bin/pusher"

if ps ax | grep -v grep | grep $process > /dev/null
then
    exit
else
    $makerun &
fi

exit
