<?php
	unset($_SESSION['gameId']);
	unset($_SESSION['max']);
	unset($_SESSION['gameName']);
	unset($_SESSION['player']);
	unset($_SESSION['map']);
	unset($_SESSION['food']);
	unset($_SESSION['production']);
	unset($_SESSION['culture']);
	unset($_SESSION['foodMax']);
	unset($_SESSION['cultureMax']);
?>